apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastdds-discovery
  namespace: messaging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastdds-discovery
  template:
    metadata:
      labels:
        app: fastdds-discovery
    spec:
      containers:
      - name: fastdds-discovery
        image: localhost/fastdds-discovery:v1
        imagePullPolicy: IfNotPresent
        command:
        - fastdds
        args:
        - discovery
        - -i
        - "0"
        - -l
        - 0.0.0.0
        - -p
        - "11811"
        ports:
        - name: discovery
          containerPort: 11811
          protocol: UDP
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: fastdds-discovery-service
  namespace: messaging
spec:
  type: NodePort
  selector:
    app: fastdds-discovery
  ports:
  - name: discovery-udp
    port: 11811
    targetPort: 11811
    protocol: UDP
    nodePort: 31811
